In [1]:
import pandas as pd
import re
from nltk.corpus import stopwords

In [2]:
stop_words = stopwords.words('english')
len(stop_words)

179

In [3]:
sms = pd.read_csv('c:/data/sms_spam1.csv')
sms

   type                                               text
0   ham                                 Hello how are you?
1   ham             I am going on a leave and sent the sms
2  spam                                 You got a lottery!
3   ham                               you look beautifully
4   ham  I  will take care of you and you take care of ...
5  spam                                         free  sms
6   ham                                         sms alerts
7   ham                            I am going to bangalore
8  spam                         apply and get 20% discount
9  spam                           pay now and get 50% off

In [4]:
docs = []
for s in sms.text:
    words = re.findall(r'\b[a-z]+\b',s.lower())
    clean_words = [w for w in words if w not in stop_words]
    docs.append(" ".join(clean_words))
docs

['hello',
 'going leave sent sms',
 'got lottery',
 'look beautifully',
 'take care take care care',
 'free sms',
 'sms alerts',
 'going bangalore',
 'apply get discount',
 'pay get']

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

In [12]:
cv = CountVectorizer(binary=True)
bow = cv.fit_transform(docs).toarray()
bow

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]])

In [13]:
cv.get_feature_names_out()

array(['alerts', 'apply', 'bangalore', 'beautifully', 'care', 'discount',
       'free', 'get', 'going', 'got', 'hello', 'leave', 'look', 'lottery',
       'pay', 'sent', 'sms', 'take'], dtype=object)

In [14]:
df_words = pd.DataFrame(bow,columns=cv.get_feature_names_out())
df_words

,alerts,apply,bangalore,beautifully,care,discount,free,get,going,got,hello,leave,look,lottery,pay,sent,sms,take
0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,1,0
2,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1
5,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0
6,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
7,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
8,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0