In [1]:
import pandas as pd
import re
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
stop_words = stopwords.words('english')
len(stop_words)

179

In [3]:
sms = pd.read_csv('c:/data/sms_spam1.csv')
sms

   type                                               text
0   ham                                 Hello how are you?
1   ham             I am going on a leave and sent the sms
2  spam                                 You got a lottery!
3   ham                               you look beautifully
4   ham  I  will take care of you and you take care of ...
5  spam                                         free  sms
6   ham                                         sms alerts
7   ham                            I am going to bangalore
8  spam                         apply and get 20% discount
9  spam                           pay now and get 50% off

In [19]:
docs = [s for s in sms.text]
docs

['Hello how are you?',
 'I am going on a leave and sent the sms',
 'You got a lottery!',
 'you look beautifully',
 'I  will take care of you and you take care of him care',
 'free  sms ',
 'sms alerts',
 'I am going to bangalore',
 'apply and get 20% discount',
 'pay now and get 50% off ']

In [41]:
cv = CountVectorizer(binary=False,token_pattern="\\b[a-z]+\\b",
                    stop_words=stop_words,lowercase=True,ngram_range=(1,1))
bow = cv.fit_transform(docs).toarray()
bow

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]])

In [37]:
cv.get_feature_names_out()

array(['alerts', 'apply', 'bangalore', 'beautifully', 'care', 'discount',
       'free', 'going', 'got', 'hello', 'leave', 'look', 'lottery', 'pay',
       'sent', 'sms'], dtype=object)

In [13]:
len(cv.get_stop_words()),len(stop_words)

(318, 179)

In [15]:
cv.get_stop_words().difference(stop_words)

frozenset({'across',
           'afterwards',
           'almost',
           'alone',
           'along',
           'already',
           'also',
           'although',
           'always',
           'among',
           'amongst',
           'amoungst',
           'amount',
           'another',
           'anyhow',
           'anyone',
           'anything',
           'anyway',
           'anywhere',
           'around',
           'back',
           'became',
           'become',
           'becomes',
           'becoming',
           'beforehand',
           'behind',
           'beside',
           'besides',
           'beyond',
           'bill',
           'bottom',
           'call',
           'cannot',
           'cant',
           'co',
           'con',
           'could',
           'couldnt',
           'cry',
           'de',
           'describe',
           'detail',
           'done',
           'due',
           'eg',
           'eight',
           'either',
           'eleven',
           'else',
           'elsewhere',
           'empty',
           'enough',
           'etc',
           'even',
           'ever',
           'every',
           'everyone',
           'everything',
           'everywhere',
           'except',
           'fifteen',
           'fifty',
           'fill',
           'find',
           'fire',
           'first',
           'five',
           'former',
           'formerly',
           'forty',
           'found',
           'four',
           'front',
           'full',
           'get',
           'give',
           'go',
           'hasnt',
           'hence',
           'hereafter',
           'hereby',
           'herein',
           'hereupon',
           'however',
           'hundred',
           'ie',
           'inc',
           'indeed',
           'interest',
           'keep',
           'last',
           'latter',
           'latterly',
           'least',
           'less',
           'ltd',
           'made',
           'many',
           'may',
           'meanwhile',
           'might',
           'mill',
           'mine',
           'moreover',
           'mostly',
           'move',
           'much',
           'must',
           'name',
           'namely',
           'neither',
           'never',
           'nevertheless',
           'next',
           'nine',
           'nobody',
           'none',
           'noone',
           'nothing',
           'nowhere',
           'often',
           'one',
           'onto',
           'others',
           'otherwise',
           'part',
           'per',
           'perhaps',
           'please',
           'put',
           'rather',
           'see',
           'seem',
           'seemed',
           'seeming',
           'seems',
           'serious',
           'several',
           'show',
           'side',
           'since',
           'sincere',
           'six',
           'sixty',
           'somehow',
           'someone',
           'something',
           'sometime',
           'sometimes',
           'somewhere',
           'still',
           'system',
           'take',
           'ten',
           'thence',
           'thereafter',
           'thereby',
           'therefore',
           'therein',
           'thereupon',
           'thick',
           'thin',
           'third',
           'though',
           'three',
           'throughout',
           'thru',
           'thus',
           'together',
           'top',
           'toward',
           'towards',
           'twelve',
           'twenty',
           'two',
           'un',
           'upon',
           'us',
           'via',
           'well',
           'whatever',
           'whence',
           'whenever',
           'whereafter',
           'whereas',
           'whereby',
           'wherein',
           'whereupon',
           'wherever',
           'whether',
           'whither',
           'whoever',
           'whole',
           'whose',
           'within',
           'without',
           'would',
           'yet'})

In [42]:
df_words = pd.DataFrame(bow,columns=cv.get_feature_names_out())
df_words

,alerts,apply,bangalore,beautifully,care,discount,free,get,going,got,hello,leave,look,lottery,pay,sent,sms,take
0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,1,0
2,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0
4,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,2
5,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0
6,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
7,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
8,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0

In [32]:
df_words.shape

(10, 10)